image: node:latest

pages:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - modulo-02-frontend/portifolio/node_modules/
  script:
    - cd modulo-02-frontend/portifolio/
    - npm install
    - npm run build
    - cd ../../
    - rm -rf public
    - mv modulo-02-frontend/portifolio/dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH