image: node:latest

pages:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - modulo-02-frontend/portifolio/node_modules/
  script:
    - cd modulo-02-frontend/portifolio/ 
    - npm run build 
    - rm -rf public 
    - mv dist public 
  artifacts:
    paths:
      - modulo-02-frontend/portifolio/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH